### PR TITLE
Dev Feature access to Source view added line 151

### PR DESCRIPTION
**Pull request by mikeadams1**
Developer status will allow you to edit root index.html files. Navigate to https://sauser.solid.community/index.html and select Source code, click the pencil to edit, delete the existing file and insert new index.html file you want to appear on root of pod, click the green check mark. Your new homepage will be created on https://suaser.solid.community and your dashboard will be on https://sauser.solid.commuinty/index/html

### CODE REVIEW

**Comment by brownhoward** [comment]
A user with any role, even the Normal User, can edit the root index.html file (based on permissions). We can include a note will instructions on how to edit the root index.html file using the Source view.

The Roles really affect only the panes/views that are visible for each resource.

**Comment by mikeadams1** [comment]
To my knowledge, a normal user cannot edit index.html in source view without selecting developer status from preferences. Not to sure about power user though.

**Comment by megoth** [comment]
A normal user don't have access to the Source view, which is what you're using to edit the HTML file. A normal user can still update the index.html through other means though (e.g. curl), so as the proposal currently stands it is easy to misinterpret.

If you believe that access to the Source view is an important part of the Developer user type, maybe you instead can change the existing point to include that as well?

**Comment by mikeadams1** [comment]
> If you believe that access to the Source view is an important part of the Developer user type, maybe you instead can change the existing point to include that as well?

Absolutely agree, in fact, more important for Developer user type to have access to Source view. That was a great feature to add @megoth. 

> A normal user can still update the index.html through other means though (e.g. curl), so as the proposal currently stands it is easy to misinterpret.

Yes, I agree, normal user can use curl to edit, among other means but, should not be able to do so via source view, I do consider that a feature.

**Comment by megoth** [comment]
I'm sorry, I misremembered earlier - The Source view is in fact available for Normal users, so no need to change to Developer user type for that.

The feature to edit index.html through the data browser is a handy one, so we will take care to allow that in the future as well. But note that how it currently is available today is not necessarily the way we will make it available in the future (the current way is kind of a hack) - but if it changes we will notify the community in advance and update [the Data Browser User Guide](https://github.com/solid/userguide).

**Comment by mikeadams1** [comment]
> The Source view is in fact available for Normal users, so no need to change to Developer user type for that.

on /index.html yes but user cannot edit it unless in developer mode, which is a feature if you ask me. Regular user should not be able to edit root /index.html unless maybe with curl or something else.

**Comment by megoth** [comment]
> > The Source view is in fact available for Normal users, so no need to change to Developer user type for that.
> 
> on /index.html yes but user cannot edit it unless in developer mode, which is a feature if you ask me.

I do not understand what you mean by "unless in developer mode" - I just edited my https://megoth.solid.community/index.html by using the WebID that I use for that Pod (https://megoth.solid.community/profile/card#me), which is not assigned the Developer user type, i.e. it's a normal user. The way you phrase it sounds like you're saying it requires Developer mode now, but do you mean that it _should_ require Developer mode?

> Regular user should not be able to edit root /index.html unless maybe with curl or something else.

Why do you argue that regular users shouldn't be able to edit index.html via the data browser?

Do you argue that we should assign the Source view as a developer view, so people will have to assign themselves the Developer user type to be able to use it?

**Comment by mikeadams1** [comment]
Ya know, I was dead wrong about that, I could have sworn that the other day I tried it on a new pod with a fellow dev and we could not get it to work unless in developer mode, my apologies. 
 

> Why do you argue that regular users shouldn't be able to edit index.html via the data browser?

I am not intentionally trying to argue the point that, a user should not be able to edit /index.html but, maybe a user should see a warning when scrolling over the Source view that indicates, any edits or changes the user may make, will effect users /index.html and dashboard. As a side note, if someone does unintentionally mess something up, at the present moment, as soon as you refresh the /index.html page and click on the Source view, click on the pencil, scroll to bottom, make a single edit of a space and then delete the space, publish by clicking the check mark, and the dashboard repopulates on root.

**Pull request closed without merging**
